# Generated by Django 5.0.4 on 2024-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='how_many_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_purchase',
            field=models.DateField(),
        ),
    ]
