# Generated by Django 5.0.4 on 2024-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_client_how_many_days_alter_client_date_of_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_of_purchase",
            field=models.DateField(auto_now_add=True),
        ),
    ]
