# Generated by Django 5.0.4 on 2024-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_name", models.CharField(max_length=100)),
                ("meal_description", models.TextField()),
                ("meal_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("meal_image", models.ImageField(upload_to="meal_images")),
                ("allergens", models.CharField(max_length=100)),
            ],
        ),
    ]
