# Generated by Django 5.0.4 on 2024-04-19 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
