# Generated by Django 5.0.4 on 2024-04-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_meal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="meal_image",
        ),
    ]
