# Generated by Django 5.0.4 on 2024-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_remove_meal_meal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="allergens",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
