# Generated by Django 5.0.4 on 2024-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_meal_allergens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="allergens",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
